### ISSUE TITLE
RuntimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by anacrolix** [catherinedevlin/ddl-generator#24]
mattjoiner@mattjoiners-LM-MBP:~$ ddlgenerator -i postgresql sample.json 
Traceback (most recent call last):
  File "/usr/local/bin/ddlgenerator", line 11, in <module>
    sys.exit(generate())
  File "/usr/local/lib/python3.5/site-packages/ddlgenerator/console.py", line 112, in generate
    generate_one(datafile, args, file=file)
  File "/usr/local/lib/python3.5/site-packages/ddlgenerator/console.py", line 58, in generate_one
    loglevel=args.log, limit=args.limit)
  File "/usr/local/lib/python3.5/site-packages/ddlgenerator/ddlgenerator.py", line 170, in __init__
    force_pk=force_pk)
  File "/usr/local/lib/python3.5/site-packages/ddlgenerator/reshape.py", line 289, in unnest_children
    for (key, val) in row.items():
RuntimeError: OrderedDict mutated during iteration

**Comment by RobertoUa** [comment]
any updates on this?
